let a;
let b;
a = 10;
b = 5;
console.log("a es", a, "b es", b);
console.log("suma:", a + b);
console.log("resta:", a - b);
console.log("multiplicación:", a * b);
console.log("división:", a / b);
console.log("resto:", a % b);
